### ISSUE TITLE
pytr downloading docs

### ISSUE THREAD

**Issue by CodingMaster3000** [marzzzello/pytr#7] opened 2021-08-17 11:08 UTC
Hello there,

I am using pytr and it worked well, but now I get an error message running pytr dl_docs 'Path'. I attached the error message.
I hope you can help me, because pytr is really useful.
[error_message.txt](https://github.com/marzzzello/pytr/files/6999410/error_message.txt)

With kind regards, CodingMaster3000

**Comment by marzzzello** [comment] 2021-08-17 11:18
Are you on the latest version?

**Comment by CodingMaster3000** [comment] 2021-08-17 11:48
No, it was 0.0.2, but i upgraded it to 0.0.4 and I still get an error message.
[error_message_2.txt](https://github.com/marzzzello/pytr/files/6999678/error_message_2.txt)

**Comment by marzzzello** [comment] 2021-08-17 13:54
So it is working but logging error messages? Then it is a duplicate of  #5

**Closed by marzzzello** 2021-08-17 13:54 UTC
